# Generated by Django 5.1.15 on 2026-08-10 16:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cartera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carteras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "cartera",
                "verbose_name_plural": "carteras",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ConjuntoCurvas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=200, verbose_name="etiqueta")),
                (
                    "valuation_date",
                    models.DateField(verbose_name="fecha de valorización"),
                ),
                (
                    "spot_usdclp",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="spot USD/CLP",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="Bloomberg", max_length=100, verbose_name="fuente"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="activo"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conjuntos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "conjunto de curvas",
                "verbose_name_plural": "conjuntos de curvas",
                "ordering": ["-valuation_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contraparte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "spread_bp",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="CDS o proxy por rating.",
                        max_digits=8,
                        verbose_name="spread de crédito (bp)",
                    ),
                ),
                (
                    "recovery",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.4,
                        max_digits=5,
                        verbose_name="tasa de recuperación",
                    ),
                ),
                (
                    "tiene_isda_neteo",
                    models.BooleanField(
                        default=True,
                        help_text="Si está activo, el CVA se calcula sobre la exposición neta.",
                        verbose_name="contrato marco con neteo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrapartes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "contraparte",
                "verbose_name_plural": "contrapartes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ContratoForward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counterparty",
                    models.CharField(max_length=100, verbose_name="contraparte"),
                ),
                (
                    "folio",
                    models.CharField(blank=True, max_length=50, verbose_name="folio"),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("Compra", "Compra"), ("Venta", "Venta")],
                        default="Venta",
                        max_length=10,
                        verbose_name="operación",
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("Compensacion", "Compensación"),
                            ("Entrega", "Entrega física"),
                        ],
                        default="Compensacion",
                        max_length=50,
                        verbose_name="modalidad",
                    ),
                ),
                (
                    "base_ccy",
                    models.CharField(
                        default="USD", max_length=10, verbose_name="moneda base"
                    ),
                ),
                (
                    "quote_ccy",
                    models.CharField(
                        default="CLP", max_length=10, verbose_name="moneda cotización"
                    ),
                ),
                (
                    "notional",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="nocional",
                    ),
                ),
                (
                    "fwd_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="precio forward pactado",
                    ),
                ),
                (
                    "spot_inicio",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Tipo de cambio vigente el día en que se pactó la operación. Se usa sólo para separar el resultado en componente spot y puntos forward.",
                        max_digits=12,
                        verbose_name="spot al inicio",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de inicio"
                    ),
                ),
                (
                    "maturity_date",
                    models.DateField(verbose_name="fecha de vencimiento"),
                ),
                (
                    "fwd_curve",
                    models.CharField(
                        default="FWDUSDCLP", max_length=50, verbose_name="curva forward"
                    ),
                ),
                (
                    "disc_curve",
                    models.CharField(
                        default="CLP423",
                        max_length=50,
                        verbose_name="curva de descuento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Vigente", "Vigente"),
                            ("Vencido", "Vencido"),
                            ("Liquidado", "Liquidado"),
                        ],
                        default="Vigente",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "cartera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos",
                        to="valorizador.cartera",
                    ),
                ),
                (
                    "contraparte_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos",
                        to="valorizador.contraparte",
                        verbose_name="contraparte (ficha)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "contrato forward",
                "verbose_name_plural": "contratos forward",
                "ordering": ["maturity_date", "counterparty"],
            },
        ),
        migrations.CreateModel(
            name="PuntoCurva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("FWDUSDCLP", "Forward USD/CLP (outright)"),
                            ("FWDEURCLP", "Forward EUR/CLP (outright)"),
                            ("CLP423", "Descuento CLP cámara"),
                            ("USD_SOFR", "Descuento USD SOFR"),
                        ],
                        max_length=50,
                        verbose_name="curva",
                    ),
                ),
                (
                    "tenor_days",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="plazo (días)",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=8, max_digits=18, verbose_name="valor"
                    ),
                ),
                (
                    "conjunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntos",
                        to="valorizador.conjuntocurvas",
                    ),
                ),
            ],
            options={
                "verbose_name": "punto de curva",
                "verbose_name_plural": "puntos de curva",
                "ordering": ["nombre", "tenor_days"],
            },
        ),
        migrations.CreateModel(
            name="ValorizacionGuardada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valuation_date",
                    models.DateField(verbose_name="fecha de valorización"),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="etiqueta"
                    ),
                ),
                (
                    "spot",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="spot usado",
                    ),
                ),
                (
                    "total_mtm",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="MtM total",
                    ),
                ),
                (
                    "total_mtm_ajustado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="MtM ajustado por crédito",
                    ),
                ),
                (
                    "total_spot",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="componente spot",
                    ),
                ),
                (
                    "total_fwdpoints",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="puntos forward",
                    ),
                ),
                (
                    "total_delta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="delta total",
                    ),
                ),
                (
                    "total_dv01",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="DV01 total",
                    ),
                ),
                (
                    "total_cva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="CVA total",
                    ),
                ),
                (
                    "total_dva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="DVA total",
                    ),
                ),
                (
                    "num_contracts",
                    models.IntegerField(
                        default=0, verbose_name="contratos valorizados"
                    ),
                ),
                (
                    "config_json",
                    models.JSONField(default=dict, verbose_name="configuración"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valorizaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "curve_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="valorizador.conjuntocurvas",
                    ),
                ),
            ],
            options={
                "verbose_name": "valorización guardada",
                "verbose_name_plural": "valorizaciones guardadas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LineaValorizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio", models.CharField(blank=True, max_length=50)),
                ("counterparty", models.CharField(max_length=100)),
                ("cartera_nombre", models.CharField(blank=True, max_length=100)),
                ("side", models.CharField(max_length=10)),
                ("maturity_date", models.DateField()),
                ("notional", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "spot_inicio",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "spot_val",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("fwd_contract", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "fwd_mkt",
                    models.DecimalField(decimal_places=6, default=0, max_digits=14),
                ),
                ("days_to_mat", models.IntegerField(default=0)),
                (
                    "year_fraction",
                    models.DecimalField(decimal_places=8, default=0, max_digits=12),
                ),
                (
                    "disc_rate",
                    models.DecimalField(decimal_places=6, default=0, max_digits=14),
                ),
                (
                    "disc_factor",
                    models.DecimalField(decimal_places=10, default=0, max_digits=18),
                ),
                (
                    "mtm",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "mtm_ajustado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "spot_component",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "fwd_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "delta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "dv01",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "theta_1d",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "cva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "dva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("flags", models.JSONField(blank=True, default=list)),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="valorizador.contratoforward",
                    ),
                ),
                (
                    "valorizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="valorizador.valorizacionguardada",
                    ),
                ),
            ],
            options={
                "verbose_name": "línea de valorización",
                "verbose_name_plural": "líneas de valorización",
                "ordering": ["maturity_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="cartera",
            constraint=models.UniqueConstraint(
                fields=("created_by", "nombre"), name="cartera_unica_por_usuario"
            ),
        ),
        migrations.AddIndex(
            model_name="conjuntocurvas",
            index=models.Index(
                fields=["created_by", "-valuation_date"],
                name="valorizador_created_7583e7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="contraparte",
            constraint=models.UniqueConstraint(
                fields=("created_by", "nombre"), name="contraparte_unica_por_usuario"
            ),
        ),
        migrations.AddIndex(
            model_name="contratoforward",
            index=models.Index(
                fields=["created_by", "status", "maturity_date"],
                name="valorizador_created_0f4c5f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="contratoforward",
            constraint=models.CheckConstraint(
                condition=models.Q(("notional__gt", 0)), name="notional_positivo"
            ),
        ),
        migrations.AddConstraint(
            model_name="contratoforward",
            constraint=models.CheckConstraint(
                condition=models.Q(("fwd_price__gt", 0)), name="precio_fwd_positivo"
            ),
        ),
        migrations.AddConstraint(
            model_name="puntocurva",
            constraint=models.UniqueConstraint(
                fields=("conjunto", "nombre", "tenor_days"),
                name="punto_unico_por_curva",
            ),
        ),
    ]
